<div class="news-letter">
			<div class="container">
				<div class="join">
					<h6> JOIN OUR MAILING LIST </h6>
					<div class="sub-left-right">
						<form>
							<input type="text" value="Enter Your Email Here" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email Here';}" />
							<input type="submit" value="SUBSCRIBE" />
						</form>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
		</div>
		
				<div class="clearfix"></div>
				</div>
		  </div>
		  <h3 style="text-align:center"> Payment Options Available </h3>
		  <div class="cards text-center">
				<img src="images/cards.jpg" alt="" />
		  </div>
		  <div class="copyright text-center">
				<p>© 2016 ATBU Teaching Hospital Bauchi. All Rights Reserved </p>
				<p> POWERD BY <a href="contributors.php"> Muhd Dembo & co.</a>
		  </div>
		</div>
		</div>
